export type HintKind = "element" | "attribute" | "property";

export interface Hint {
  kind: HintKind;
  kindLabel: string;
  title: string;
  body: string;
  example: string;
}

/**
 * Seed dictionary. Intentionally partial — new entries are welcome.
 * Keys are lowercased tag / attribute / property names exactly as they appear
 * in the source. Content is in French and pedagogical.
 */
export const HTML_HINTS: Record<string, Hint> = {
  html: {
    kind: "element",
    kindLabel: "balise",
    title: "<html>",
    body: "La racine de tout document HTML. Tout le reste vit à l'intérieur.",
    example: `<html lang="fr">\n  …\n</html>`,
  },
  head: {
    kind: "element",
    kindLabel: "balise",
    title: "<head>",
    body: "Contient les métadonnées de la page : titre, feuilles de style, polices. Rien n'y est visible à l'écran.",
    example: `<head>\n  <title>Ma page</title>\n</head>`,
  },
  title: {
    kind: "element",
    kindLabel: "balise",
    title: "<title>",
    body: "Le texte qui apparaît dans l'onglet du navigateur et les résultats de recherche.",
    example: `<title>Mon premier site</title>`,
  },
  body: {
    kind: "element",
    kindLabel: "balise",
    title: "<body>",
    body: "Le contenu visible de la page — tout ce qu'un visiteur peut voir.",
    example: `<body>\n  <h1>Bonjour !</h1>\n</body>`,
  },
  meta: {
    kind: "element",
    kindLabel: "balise",
    title: "<meta>",
    body: "Donne au navigateur des infos sur la page. charset='utf-8' autorise tous les caractères Unicode.",
    example: `<meta charset="utf-8">`,
  },
  link: {
    kind: "element",
    kindLabel: "balise",
    title: "<link>",
    body: "Relie la page à une ressource externe — le plus souvent une feuille de style CSS. Auto-fermante.",
    example: `<link rel="stylesheet" href="style.css">`,
  },
  header: {
    kind: "element",
    kindLabel: "balise",
    title: "<header>",
    body: "Conteneur sémantique pour le haut d'une page ou d'une section — souvent un logo et un titre.",
    example: `<header>\n  <h1>Mon site</h1>\n</header>`,
  },
  nav: {
    kind: "element",
    kindLabel: "balise",
    title: "<nav>",
    body: "Regroupe les liens de navigation principaux d'une page.",
    example: `<nav>\n  <a href="/">Accueil</a>\n</nav>`,
  },
  main: {
    kind: "element",
    kindLabel: "balise",
    title: "<main>",
    body: "Le contenu principal de la page. Utilisez un seul <main> par page.",
    example: `<main>\n  …contenu principal…\n</main>`,
  },
  section: {
    kind: "element",
    kindLabel: "balise",
    title: "<section>",
    body: "Une zone thématique de la page, généralement introduite par un titre.",
    example: `<section>\n  <h2>À propos</h2>\n</section>`,
  },
  article: {
    kind: "element",
    kindLabel: "balise",
    title: "<article>",
    body: "Un contenu indépendant qui pourrait être distribué seul (billet de blog, fiche produit…).",
    example: `<article>\n  <h2>Titre</h2>\n  <p>Contenu…</p>\n</article>`,
  },
  footer: {
    kind: "element",
    kindLabel: "balise",
    title: "<footer>",
    body: "Le bas d'une page ou d'une section — souvent copyright ou liens secondaires.",
    example: `<footer>© 2026</footer>`,
  },
  div: {
    kind: "element",
    kindLabel: "balise",
    title: "<div>",
    body: "Conteneur générique bloc, sans sens sémantique. Préférez une balise sémantique quand possible.",
    example: `<div class="card">…</div>`,
  },
  span: {
    kind: "element",
    kindLabel: "balise",
    title: "<span>",
    body: "Conteneur inline sans sens visuel — sert à styler ou scripter un morceau de texte.",
    example: `<span class="accent">mot</span>`,
  },
  h1: {
    kind: "element",
    kindLabel: "balise",
    title: "<h1>",
    body: "Le titre principal de la page. Un seul <h1> par page.",
    example: `<h1>Bonjour le monde</h1>`,
  },
  h2: {
    kind: "element",
    kindLabel: "balise",
    title: "<h2>",
    body: "Titre de deuxième niveau, pour les grandes sections.",
    example: `<h2>À propos</h2>`,
  },
  h3: {
    kind: "element",
    kindLabel: "balise",
    title: "<h3>",
    body: "Titre de troisième niveau. Utilisez les niveaux dans l'ordre.",
    example: `<h3>Sous-section</h3>`,
  },
  p: {
    kind: "element",
    kindLabel: "balise",
    title: "<p>",
    body: "Un paragraphe de texte. Les navigateurs ajoutent un espace au-dessus et en dessous.",
    example: `<p>Quelques mots ici.</p>`,
  },
  a: {
    kind: "element",
    kindLabel: "balise",
    title: "<a>",
    body: "Un lien hypertexte. L'attribut href indique où il pointe.",
    example: `<a href="/contact">Me contacter</a>`,
  },
  img: {
    kind: "element",
    kindLabel: "balise",
    title: "<img>",
    body: "Insère une image. src pointe vers le fichier, alt décrit l'image pour l'accessibilité.",
    example: `<img src="logo.svg" alt="Logo">`,
  },
  ul: {
    kind: "element",
    kindLabel: "balise",
    title: "<ul>",
    body: "Liste à puces. Chaque élément est une balise <li>.",
    example: `<ul>\n  <li>Un</li>\n  <li>Deux</li>\n</ul>`,
  },
  ol: {
    kind: "element",
    kindLabel: "balise",
    title: "<ol>",
    body: "Liste ordonnée (numérotée). Chaque élément est une balise <li>.",
    example: `<ol>\n  <li>Premier</li>\n  <li>Deuxième</li>\n</ol>`,
  },
  li: {
    kind: "element",
    kindLabel: "balise",
    title: "<li>",
    body: "Un élément de liste, à placer dans un <ul> ou un <ol>.",
    example: `<li>Item</li>`,
  },
  button: {
    kind: "element",
    kindLabel: "balise",
    title: "<button>",
    body: "Un bouton cliquable. Utilisez type='button' pour un clic pur, 'submit' pour un formulaire.",
    example: `<button type="button">Cliquer</button>`,
  },
  form: {
    kind: "element",
    kindLabel: "balise",
    title: "<form>",
    body: "Conteneur de formulaire. action = URL où envoyer les données, method = GET ou POST.",
    example: `<form action="/submit" method="post">\n  …\n</form>`,
  },
  input: {
    kind: "element",
    kindLabel: "balise",
    title: "<input>",
    body: "Un champ de saisie. L'attribut type détermine le genre (text, email, number, checkbox, …).",
    example: `<input type="text" name="prenom">`,
  },
  em: {
    kind: "element",
    kindLabel: "balise",
    title: "<em>",
    body: "Emphase sur un mot. Rendu en italique par défaut.",
    example: `Je suis <em>vraiment</em> content.`,
  },
  strong: {
    kind: "element",
    kindLabel: "balise",
    title: "<strong>",
    body: "Importance forte. Rendu en gras par défaut.",
    example: `<strong>Attention !</strong>`,
  },

  // attributes
  lang: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "lang",
    body: "Indique la langue du contenu. Utile pour les moteurs de recherche et les lecteurs d'écran.",
    example: `<html lang="fr">`,
  },
  class: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "class",
    body: "Une étiquette posée sur un élément pour que le CSS (ou le JS) puisse le retrouver.",
    example: `<p class="lede">…</p>`,
  },
  id: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "id",
    body: "Un identifiant unique pour un élément. Un seul id par valeur dans toute la page.",
    example: `<section id="a-propos">…</section>`,
  },
  rel: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "rel",
    body: "Décrit la relation d'un <link>. 'stylesheet' signifie 'ce fichier habille ma page'.",
    example: `rel="stylesheet"`,
  },
  href: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "href",
    body: "Le chemin de la ressource. Peut être un fichier local ou une URL complète.",
    example: `href="style.css"`,
  },
  src: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "src",
    body: "Le chemin d'une ressource à charger (image, script, iframe).",
    example: `src="image.png"`,
  },
  alt: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "alt",
    body: "Texte alternatif d'une image, lu par les lecteurs d'écran et affiché si l'image ne charge pas.",
    example: `alt="Logo de WeCode"`,
  },
  type: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "type",
    body: "Selon la balise : pour <input> c'est le genre de champ, pour <button> le comportement, pour <script> le type MIME.",
    example: `<input type="email">`,
  },
  name: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "name",
    body: "Le nom d'un champ de formulaire — c'est sous ce nom que sa valeur est envoyée.",
    example: `<input name="email">`,
  },
  value: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "value",
    body: "La valeur initiale d'un champ de formulaire.",
    example: `<input value="hello">`,
  },
  placeholder: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "placeholder",
    body: "Texte d'aide visible tant que le champ est vide. Ne remplace pas un <label>.",
    example: `<input placeholder="votre email">`,
  },
  charset: {
    kind: "attribute",
    kindLabel: "attribut",
    title: "charset",
    body: "Encodage de caractères du document. Mettre 'utf-8' couvre quasiment tout.",
    example: `<meta charset="utf-8">`,
  },
};

export const CSS_HINTS: Record<string, Hint> = {
  color: {
    kind: "property",
    kindLabel: "propriété",
    title: "color",
    body: "Couleur du texte d'un élément. Accepte un nom, un code hex, rgb(), hsl(), oklch()…",
    example: `color: #0066cc;`,
  },
  background: {
    kind: "property",
    kindLabel: "propriété",
    title: "background",
    body: "Raccourci qui règle la couleur et l'image de fond d'un élément.",
    example: `background: #f4f4f5;`,
  },
  "background-color": {
    kind: "property",
    kindLabel: "propriété",
    title: "background-color",
    body: "Couleur de fond d'un élément.",
    example: `background-color: white;`,
  },
  "font-family": {
    kind: "property",
    kindLabel: "propriété",
    title: "font-family",
    body: "Famille de polices à utiliser. On met plusieurs polices séparées par des virgules, du préféré au secours.",
    example: `font-family: "Geist", sans-serif;`,
  },
  "font-size": {
    kind: "property",
    kindLabel: "propriété",
    title: "font-size",
    body: "Taille de la police. Utilise px, em, rem selon le cas.",
    example: `font-size: 16px;`,
  },
  "font-weight": {
    kind: "property",
    kindLabel: "propriété",
    title: "font-weight",
    body: "Graisse du texte. 400 = normal, 700 = gras. On peut aussi écrire 'normal' ou 'bold'.",
    example: `font-weight: 600;`,
  },
  "line-height": {
    kind: "property",
    kindLabel: "propriété",
    title: "line-height",
    body: "Hauteur d'une ligne de texte. Utilise un nombre sans unité (1.5) pour que ça s'adapte à font-size.",
    example: `line-height: 1.5;`,
  },
  padding: {
    kind: "property",
    kindLabel: "propriété",
    title: "padding",
    body: "Espace intérieur, entre le contenu et le bord de l'élément.",
    example: `padding: 12px 16px;`,
  },
  margin: {
    kind: "property",
    kindLabel: "propriété",
    title: "margin",
    body: "Espace extérieur, entre cet élément et ses voisins.",
    example: `margin: 0 auto;`,
  },
  border: {
    kind: "property",
    kindLabel: "propriété",
    title: "border",
    body: "Raccourci pour la bordure : épaisseur, style, couleur.",
    example: `border: 1px solid #ddd;`,
  },
  "border-radius": {
    kind: "property",
    kindLabel: "propriété",
    title: "border-radius",
    body: "Arrondi des coins d'un élément.",
    example: `border-radius: 8px;`,
  },
  display: {
    kind: "property",
    kindLabel: "propriété",
    title: "display",
    body: "Détermine comment l'élément se comporte : block, inline, flex, grid…",
    example: `display: flex;`,
  },
  flex: {
    kind: "property",
    kindLabel: "propriété",
    title: "flex",
    body: "Raccourci dans un contexte flex pour dire combien l'élément peut grandir, rétrécir et sa taille de base.",
    example: `flex: 1 1 auto;`,
  },
  gap: {
    kind: "property",
    kindLabel: "propriété",
    title: "gap",
    body: "Espacement entre les enfants d'un conteneur flex ou grid. Plus simple que margin.",
    example: `gap: 12px;`,
  },
  width: {
    kind: "property",
    kindLabel: "propriété",
    title: "width",
    body: "Largeur de l'élément. Accepte px, %, vw, auto, min-content…",
    example: `width: 100%;`,
  },
  height: {
    kind: "property",
    kindLabel: "propriété",
    title: "height",
    body: "Hauteur de l'élément.",
    example: `height: 100vh;`,
  },
  position: {
    kind: "property",
    kindLabel: "propriété",
    title: "position",
    body: "Mode de positionnement : static (défaut), relative, absolute, fixed, sticky.",
    example: `position: relative;`,
  },
  "text-align": {
    kind: "property",
    kindLabel: "propriété",
    title: "text-align",
    body: "Alignement horizontal du texte : left, right, center, justify.",
    example: `text-align: center;`,
  },
};
