export type HintKind = "element" | "attribute" | "property";

export interface Hint {
  kind: HintKind;
  kindLabel: string;
  title: string;
  body: string;
  example: string;
}

/**
 * Seed dictionary. Intentionally partial — new entries are welcome.
 * Keys are lowercased tag / attribute / property names exactly as they appear
 * in the source. Content is in English and pedagogical.
 */
export const HTML_HINTS: Record<string, Hint> = {
  html: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<html>",
    body: "The root of every HTML document. Everything else lives inside it.",
    example: `<html lang="en">\n  …\n</html>`,
  },
  head: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<head>",
    body: "Contains the page's metadata: title, stylesheets, fonts. Nothing here is visible on screen.",
    example: `<head>\n  <title>My page</title>\n</head>`,
  },
  title: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<title>",
    body: "The text that appears in the browser tab and search results.",
    example: `<title>My first site</title>`,
  },
  body: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<body>",
    body: "The visible content of the page — everything a visitor can see.",
    example: `<body>\n  <h1>Hello!</h1>\n</body>`,
  },
  meta: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<meta>",
    body: "Gives the browser information about the page. charset='utf-8' enables all Unicode characters.",
    example: `<meta charset="utf-8">`,
  },
  link: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<link>",
    body: "Connects the page to an external resource — most often a CSS stylesheet. Self-closing.",
    example: `<link rel="stylesheet" href="style.css">`,
  },
  header: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<header>",
    body: "Semantic container for the top of a page or section — often a logo and a title.",
    example: `<header>\n  <h1>My site</h1>\n</header>`,
  },
  nav: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<nav>",
    body: "Groups the main navigation links of a page.",
    example: `<nav>\n  <a href="/">Home</a>\n</nav>`,
  },
  main: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<main>",
    body: "The primary content of the page. Use only one <main> per page.",
    example: `<main>\n  …main content…\n</main>`,
  },
  section: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<section>",
    body: "A thematic area of the page, usually introduced by a heading.",
    example: `<section>\n  <h2>About</h2>\n</section>`,
  },
  article: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<article>",
    body: "Self-contained content that could stand on its own (blog post, product card…).",
    example: `<article>\n  <h2>Title</h2>\n  <p>Content…</p>\n</article>`,
  },
  footer: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<footer>",
    body: "The bottom of a page or section — often copyright or secondary links.",
    example: `<footer>© 2026</footer>`,
  },
  div: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<div>",
    body: "Generic block container with no semantic meaning. Prefer a semantic tag when possible.",
    example: `<div class="card">…</div>`,
  },
  span: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<span>",
    body: "Inline container with no visual meaning — used to style or script a piece of text.",
    example: `<span class="accent">word</span>`,
  },
  h1: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<h1>",
    body: "The main heading of the page. Use only one <h1> per page.",
    example: `<h1>Hello world</h1>`,
  },
  h2: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<h2>",
    body: "Second-level heading, for major sections.",
    example: `<h2>About</h2>`,
  },
  h3: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<h3>",
    body: "Third-level heading. Use heading levels in order.",
    example: `<h3>Subsection</h3>`,
  },
  p: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<p>",
    body: "A paragraph of text. Browsers add spacing above and below by default.",
    example: `<p>A few words here.</p>`,
  },
  a: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<a>",
    body: "A hyperlink. The href attribute indicates where it points.",
    example: `<a href="/contact">Contact me</a>`,
  },
  img: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<img>",
    body: "Inserts an image. src points to the file, alt describes the image for accessibility.",
    example: `<img src="logo.svg" alt="Logo">`,
  },
  ul: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<ul>",
    body: "Bulleted list. Each item is a <li> tag.",
    example: `<ul>\n  <li>One</li>\n  <li>Two</li>\n</ul>`,
  },
  ol: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<ol>",
    body: "Ordered (numbered) list. Each item is a <li> tag.",
    example: `<ol>\n  <li>First</li>\n  <li>Second</li>\n</ol>`,
  },
  li: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<li>",
    body: "A list item, placed inside a <ul> or an <ol>.",
    example: `<li>Item</li>`,
  },
  button: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<button>",
    body: "A clickable button. Use type='button' for a plain click, 'submit' for a form.",
    example: `<button type="button">Click me</button>`,
  },
  form: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<form>",
    body: "Form container. action = URL to send data to, method = GET or POST.",
    example: `<form action="/submit" method="post">\n  …\n</form>`,
  },
  input: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<input>",
    body: "An input field. The type attribute determines its kind (text, email, number, checkbox, …).",
    example: `<input type="text" name="firstname">`,
  },
  em: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<em>",
    body: "Emphasis on a word. Rendered in italics by default.",
    example: `I am <em>really</em> happy.`,
  },
  strong: {
    kind: "element",
    kindLabel: "HTML Element",
    title: "<strong>",
    body: "Strong importance. Rendered in bold by default.",
    example: `<strong>Warning!</strong>`,
  },

  // attributes
  lang: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "lang",
    body: "Indicates the language of the content. Useful for search engines and screen readers.",
    example: `<html lang="en">`,
  },
  class: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "class",
    body: "A label on an element so CSS (or JS) can target it.",
    example: `<p class="lede">…</p>`,
  },
  id: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "id",
    body: "A unique identifier for an element. Each id value must appear only once per page.",
    example: `<section id="about">…</section>`,
  },
  rel: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "rel",
    body: "Describes the relationship of a <link>. 'stylesheet' means 'this file styles my page'.",
    example: `rel="stylesheet"`,
  },
  href: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "href",
    body: "The path to the resource. Can be a local file or a full URL.",
    example: `href="style.css"`,
  },
  src: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "src",
    body: "The path to a resource to load (image, script, iframe).",
    example: `src="image.png"`,
  },
  alt: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "alt",
    body: "Alternative text for an image, read by screen readers and shown if the image fails to load.",
    example: `alt="WeCode logo"`,
  },
  type: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "type",
    body: "Depends on the tag: for <input> it's the field kind, for <button> the behavior, for <script> the MIME type.",
    example: `<input type="email">`,
  },
  name: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "name",
    body: "The name of a form field — its value is submitted under this name.",
    example: `<input name="email">`,
  },
  value: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "value",
    body: "The initial value of a form field.",
    example: `<input value="hello">`,
  },
  placeholder: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "placeholder",
    body: "Helper text visible while the field is empty. Does not replace a <label>.",
    example: `<input placeholder="your email">`,
  },
  charset: {
    kind: "attribute",
    kindLabel: "HTML Attribute",
    title: "charset",
    body: "Character encoding of the document. Setting 'utf-8' covers virtually everything.",
    example: `<meta charset="utf-8">`,
  },
};

export const CSS_HINTS: Record<string, Hint> = {
  color: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "color",
    body: "Text color of an element. Accepts a name, hex code, rgb(), hsl(), oklch()…",
    example: `color: #0066cc;`,
  },
  background: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "background",
    body: "Shorthand that sets the background color and image of an element.",
    example: `background: #f4f4f5;`,
  },
  "background-color": {
    kind: "property",
    kindLabel: "CSS Property",
    title: "background-color",
    body: "Background color of an element.",
    example: `background-color: white;`,
  },
  "font-family": {
    kind: "property",
    kindLabel: "CSS Property",
    title: "font-family",
    body: "Font family to use. List multiple fonts separated by commas, from preferred to fallback.",
    example: `font-family: "Geist", sans-serif;`,
  },
  "font-size": {
    kind: "property",
    kindLabel: "CSS Property",
    title: "font-size",
    body: "Font size. Use px, em, or rem depending on context.",
    example: `font-size: 16px;`,
  },
  "font-weight": {
    kind: "property",
    kindLabel: "CSS Property",
    title: "font-weight",
    body: "Text weight. 400 = normal, 700 = bold. You can also write 'normal' or 'bold'.",
    example: `font-weight: 600;`,
  },
  "line-height": {
    kind: "property",
    kindLabel: "CSS Property",
    title: "line-height",
    body: "Height of a line of text. Use a unitless number (1.5) so it scales with font-size.",
    example: `line-height: 1.5;`,
  },
  padding: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "padding",
    body: "Inner spacing, between the content and the element's border.",
    example: `padding: 12px 16px;`,
  },
  margin: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "margin",
    body: "Outer spacing, between this element and its neighbors.",
    example: `margin: 0 auto;`,
  },
  border: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "border",
    body: "Shorthand for the border: thickness, style, color.",
    example: `border: 1px solid #ddd;`,
  },
  "border-radius": {
    kind: "property",
    kindLabel: "CSS Property",
    title: "border-radius",
    body: "Rounds the corners of an element.",
    example: `border-radius: 8px;`,
  },
  display: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "display",
    body: "Determines how the element behaves: block, inline, flex, grid…",
    example: `display: flex;`,
  },
  flex: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "flex",
    body: "Shorthand in a flex context to set how much an item can grow, shrink, and its base size.",
    example: `flex: 1 1 auto;`,
  },
  gap: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "gap",
    body: "Spacing between children of a flex or grid container. Simpler than margin.",
    example: `gap: 12px;`,
  },
  width: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "width",
    body: "Width of the element. Accepts px, %, vw, auto, min-content…",
    example: `width: 100%;`,
  },
  height: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "height",
    body: "Height of the element.",
    example: `height: 100vh;`,
  },
  position: {
    kind: "property",
    kindLabel: "CSS Property",
    title: "position",
    body: "Positioning mode: static (default), relative, absolute, fixed, sticky.",
    example: `position: relative;`,
  },
  "text-align": {
    kind: "property",
    kindLabel: "CSS Property",
    title: "text-align",
    body: "Horizontal text alignment: left, right, center, justify.",
    example: `text-align: center;`,
  },
};
